url=https://www.urbanladder.com/  
chrome=C:\\Users\\Ks4u\\git\\Code_Automation1\\Automation\\Drivers\\chromedriver.exe
firefox=C:\\Users\\Ks4u\\git\\Code_Automation1\\Automation\\Drivers\\geckodriver.exe
Close=Close
search=search
bookshelf=bookshelf
enter=//*[@id='search_button']/span
upper=//*[@id='filters-form']/div[1]/div/div/ul/li[2]/div[2]/div/div/ul/li[1]/div/div[2]/div[2]/div/div[2]/div
price=//*[@id='filters-form']/div[1]/div/div/ul/li[2]/div[1]
stock=/html/body/div[1]/div[1]/div[2]/div[1]/div[2]/div[1]/div/form/div[2]/div/input
storage=//*[@id='filters-form']/div[1]/div/div/ul/li[3]/div[1]
check=/html/body/div[1]/div[1]/div[2]/div[1]/div[2]/div[1]/div/form/div[1]/div/div/ul/li[3]/div[2]/div/div/div/ul/li[1]/input
chairsearch=search
filter=filters_primary_category_Study_Chair
productTitle=//a[contains(text(),'Being At Home')]/parent::*/following-sibling::ul/li
chairTitle=product-title-sofa-mattresses
chairPrice=price-number
shelvesTitle=product-title-sofa-mattresses
shelvesPrice=price-number
