
#WebSite URL
url=https://www.urbanladder.com/  

#WebDrivers
chrome=\\Drivers\\chromedriver.exe
firefox=\\Drivers\\geckodriver.exe

#Browsers
browser=chrome

#Pop Close
Close=Close

#SendKeys
chairsearch1=Study Chair
Search1=bookshelf
password=3abc
username=anu23@

#Searching BookShelf
Search=search
enter=//*[@id='search_button']/span
price=//*[@data-group='price']/div[@class='gname']
price1=//div[@class='noUi-base']//div[@class='noUi-handle noUi-handle-upper']

#Storage Type
storage=//*[@data-group='storage type']/div[@class='gname']
open=//*[@id='filters_storage_type_Open']
		
#Out Of Stock
stock=//*[@id='filters_availability_In_Stock_Only']

#Printing The BookShelf
shelvesTitle=product-title-sofa-mattresses
shelvesPrice=price-number

#StudyChair
chairsearch=search

#Printing The StudyChair
TableName=//span[@itemprop="name"]
TablePrice=//div[@class="price-number"]

#Sales
sale=//*[@class='topnav_item saleunit']/span
productOff=//*[@class='subnav_item 14085']/a/span

#Cart
cart=//*[@id='cart-badge']
cartTitle=//*[@class='empty_msg']

#Login
checkAcc=//*[@id='shortlist-badge']
checkUser=//*[@id='spree_user_email']


