url=https://www.urbanladder.com/
chrome=\\Drivers\\chromedriver.exe
firefox=\\Drivers\\geckodriver.exe
search=search
enter=//*[@id='search_button']/span
price=//*[@id='filters-form']/div[1]/div/div/ul/li[2]/div[1]
stock=/html/body/div[1]/div[1]/div[2]/div[1]/div[2]/div[1]/div/form/div[2]/div/input
storage=//*[@id='filters-form']/div[1]/div/div/ul/li[3]/div[1]
chairsearch=search
filter=filters_primary_category_Study_Chair
productTitle=//a[contains(text(),'Being At Home')]/parent::*/following-sibling::ul/li
chairTitle=product-title-sofa-mattresses
chairPrice=price-number
shelvesTitle=product-title-sofa-mattresses
shelvesPrice=price-number
chairsearch1=Study Chair
chairsearch=search
TableName=//span[@itemprop="name"]
TablePrice=//div[@class="price-number"]
