
#WebSite URL
url=https://www.urbanladder.com/  

#WebDrivers
chrome=\\Drivers\\chromedriver.exe
firefox=\\Drivers\\geckodriver.exe

#Pop Close
Close=Close

#SendKeys
chairsearch1=Study Chair
Search1=bookshelf

#Searching BookShelf
Search=search
enter=//*[@id='search_button']/span
price=//*[@id='filters-form']/div[1]/div/div/ul/li[2]/div[1]
price1=//*[@id='filters-form']/div[1]/div/div/ul/li[2]/div[2]/div/div/ul/li[1]/div/div[2]/div[2]/div/div[2]/div

#Storage Type
storage=//*[@id='filters-form']/div[1]/div/div/ul/li[3]/div[1]
open=//*[@id='filters_storage_type_Open']
		
#Out Of Stock
stock=//*[@id='filters_availability_In_Stock_Only']

#Printing The BookShelf
shelvesTitle=product-title-sofa-mattresses
shelvesPrice=price-number

#StudyChair
chairsearch=search

#Printing The StudyChair
TableName=//span[@itemprop="name"]
TablePrice=//div[@class="price-number"]

#Sales
sale=//*[@id='topnav_wrapper']/ul/li[1]/span
productOff=//*[@id='topnav_wrapper']/ul/li[1]/div/div/ul/li[2]/ul/li[1]/a/span

#Cart
cart=//*[@id='cart-badge']
cartTitle=//*[@id='content']/div/div[2]/p[1]

#Login
checkAcc=//*[@id='account-logged-out']/li[2]/a
checkUser=//*[@id='spree_user_email']
username=anu23@
checkPssd=//*[@id='spree_user_password']
password=123abc
checkSubmit=//*[@id='ul_site_login']

